### PR TITLE
[WIP] Travis: Build for a few different architectures

### PR DESCRIPTION
**Pull request by genodeftest**
This pull request is WIP because I don't know the docker names for these architectures so I just guessed them.
The tests will probably fail, see issue #8.

### CODE REVIEW

**Comment by genodeftest** [comment]
@sjohannes : Do you know where to get the names for linux images from other arches? I guess I chose them incorrectly, but I could not find anything on the internet which are the right ones.

Travis recognized the following architectures (first name is fedora's name, second name is travis' name):
* [x] x86_64: `linux`
* [ ] i686 (tried: `linux-686`, `linux-i686`)
* [ ] s390x (tried: `linux-390x`, `linux-s390x`)
* [ ] aarch64 (tried: `linux-aarch64`, `linux-arm64`)
* [ ] armv7hl (tried: `linux-arrmv7hl`, `linux-armv7`)
* [x] ppc64le: `linux-ppc64le`

**Comment by genodeftest** [comment]
The ppc64le build may fail because wine does not work on ppc64le. Maybe the windows target should be specified separately.

**Comment by sjohannes** [comment]
I think Travis only has x86_64 and ppc64le builders for now, and the latter is [not supported](https://travis-ci.community/t/ppc64le-arch-support-on-travis-ci-com-vs-travis-ci-org/2898).

[The error you're getting](https://travis-ci.org/exaile/moodbar/jobs/525300582#L237) may be related to Docker's [confusing multiarch support](https://developer.ibm.com/linuxonpower/2017/07/27/create-multi-architecture-docker-image/). As far as I can tell, Docker Hub's autobuilder [can only build x64_64 images](https://blog.slucas.fr/blog/docker-multiarch-manifest-hub-2/), so we'd have to build the images elsewhere (e.g. on Travis) and then push them to Docker Hub.

All in all it feels like too much work....

**Comment by genodeftest** [comment]
@sjohannes wrote:
> All in all it feels like too much work....

+1 on that. Let's give it up.

**Pull request closed without merging**
